{% set name = "pytango" %}
{% set version = "9.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/pytango/-/archive/v{{ version }}/pytango-v{{ version }}.tar.gz
  sha256: 2cdbcbf36858e5dba7a26f5fa4cdf3dbcd4a8c1a291cb1d729f87c9302621846
  patches:
    - cmake-win.patch  # [win]

build:
  number: 0
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=9.3,<9.4.0a0
    - boost
    - numpy >=1.1
    - omniorb
  run:
    # cpptango set in run_exports
    - python
    # boost max_pin set in pin_run_as_build in conda-forge-pinning
    - boost
    - {{ pin_compatible('numpy') }}
    - six >=1.10
    - enum34  # [py==27]

test:
  requires:   # [unix]
    - pytest                # [unix]
    - pytest-xdist          # [unix]
    - gevent                # [unix]
    - psutil                # [unix]
    - trollius              # [unix and py==27]
    - tango-test=3.2        # [unix]
  source_files:   # [unix]
    - tests/                # [unix]
    - setup.cfg             # [unix]
  imports:
    - PyTango
    - tango
  commands:   # [unix]
    - pytest                # [unix]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE.txt
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
