{% set name = "pytango" %}
{% set version = "9.5.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53bfdf00a89bc207174eeccd373bf6e9a109f1d3c673761235f8904cdb614bd3

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
    - cmake
    - ninja       # [unix]
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=9.5.0,<9.6.0a0
    - libboost-python-devel
    - numpy
    - omniorb-libs
    - scikit-build-core
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - packaging
    - psutil

test:
  requires:                 # [unix]
    - pytest                # [unix]
    - pytest-forked         # [unix]
    - gevent                # [unix]
    - tango-test=3.8        # [unix]
  source_files:             # [unix]
    - tests/                # [unix]
  imports:
    - PyTango
    - tango
  commands:                 # [unix]
    - pytest -v --forked    # [unix]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE.txt
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
