{% set name = "pytango" %}
{% set version = "9.4.0rc3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecfa8e2bfb2fe51edf1e066b1848fedd6bfe84a3af3af0bb707edbb3d5899d8b
  patches:
    - cmake-win.patch             # [win]

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=9.4,<9.5.0a0
    - boost
    - numpy
    - omniorb-libs
  run:
    # cpptango set in run_exports
    - python
    # boost max_pin set in pin_run_as_build in conda-forge-pinning
    - boost
    - {{ pin_compatible('numpy') }}
    - packaging
    - psutil

test:
  requires:                 # [unix]
    - pytest                # [unix]
    - pytest-forked         # [unix]
    - gevent                # [unix]
    - psutil                # [unix]
    - tango-test=3.6        # [unix]
  source_files:             # [unix]
    - tests/                # [unix]
    - setup.cfg             # [unix]
  imports:
    - PyTango
    - tango
  commands:                 # [unix]
    - pytest                # [unix]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE.txt
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
