{% set name = "pytango" %}
{% set version = "9.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a75113a4ff15232c938fbf40240fbdffea0140e1af7b24366ecec0e2921bc634
  patches:
    - 0001-Fix-psutil-DeprecationWarning.patch

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config  # [unix]
    - cmake
    - make        # [unix]
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=9.5.0,<9.6.0a0
    - libboost-python-devel
    - numpy
    - omniorb-libs
    - scikit-build-core
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - packaging
    - psutil

test:
  requires:   # [unix]
    - pytest                # [unix]
    - pytest-asyncio        # [unix]
    - pytest-forked         # [unix]
    - gevent                # [unix]
    - tango-test=3.8        # [unix]
  source_files:   # [unix]
    - tests/                # [unix]
  imports:
    - PyTango
    - tango
  commands:   # [unix]
    # Skip test_subscribe_data_ready_event on aarch64 for now
    # (fails most of the time)
    - pytest -v --forked                                           # [unix and not aarch64]
    - pytest -v --forked -k "not test_subscribe_data_ready_event"  # [aarch64]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE.txt
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - yamedvedya
    - beenje
    - ajoubertza
