{% set name = "pytango" %}
{% set version = "9.4.0rc1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 942906fcf8dbed807139a97c0e21177339383693277e34f92bc8623ad3d16103
  patches:
    - cmake-win.patch             # [win]

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=9.4,<9.5.0a0
    - boost
    - numpy >=1.13.3
    - omniorb-libs
  run:
    # cpptango set in run_exports
    - python
    # boost max_pin set in pin_run_as_build in conda-forge-pinning
    - boost
    - {{ pin_compatible('numpy') }}
    - six >=1.10

test:
  requires:                 # [unix]
    - pytest                # [unix]
    - pytest-forked         # [unix]
    - gevent                # [unix]
    - psutil                # [unix]
    - tango-test=3.6        # [unix]
  source_files:             # [unix]
    - tests/                # [unix]
    - setup.cfg             # [unix]
  imports:
    - PyTango
    - tango
  commands:                 # [unix]
    - pytest                # [unix]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE.txt
    - LICENSE.cpython
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
