{% set name = "pytango" %}
{% set version = "9.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 61d9c47f6fcdaa747024768b2926cf90db1be213dd6e74ee9de50e146d328fa7
  patches:
    - cmake-win.patch             # [win]

build:
  number: 1
  skip: true  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=9.4.1,<9.5.0a0
    - libboost-python-devel
    - numpy
    - omniorb-libs
  run:
    # cpptango set in run_exports
    - python
    - {{ pin_compatible('numpy') }}
    - packaging
    - psutil

test:
  requires:                 # [unix]
    - pytest                # [unix]
    - pytest-forked         # [unix]
    - gevent                # [unix]
    - tango-test=3.7        # [unix]
  source_files:             # [unix]
    - tests/                # [unix]
    - setup.cfg             # [unix]
  imports:
    - PyTango
    - tango
  commands:                 # [unix]
    # Skip test_subscribe_data_ready_event on aarch64 for now
    # (fails most of the time)
    - pytest                                           # [unix and not aarch64]
    - pytest -k "not test_subscribe_data_ready_event"  # [aarch64]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE.txt
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
