{% set name = "pytango" %}
{% set version = "10.0.0rc4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39475804c261fe7a19dd90bb45f9b47c54bb0b357e6b4fceaf6622d5cffc5d20

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - pkg-config  # [unix]
    - cmake
    - make        # [unix]
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=10.0.0rc6,<10.1.0a0
    - libboost-python-devel
    - numpy
    - omniorb-libs
    - scikit-build-core
    - pybind11-stubgen
  run:
    - python
    - packaging
    - psutil >=5.3.0
    - opentelemetry-api                       # [unix]
    - opentelemetry-sdk                       # [unix]
    - opentelemetry-exporter-otlp-proto-grpc  # [unix]
    - opentelemetry-exporter-otlp-proto-http  # [unix]

test:
  requires:                 # [unix]
    - pytest                # [unix]
    - pytest-asyncio        # [unix]
    - pytest-forked         # [unix]
    - gevent                # [unix]
    - tango-test=3.9        # [unix]
  source_files:             # [unix]
    - tests/                # [unix]
  imports:
    - PyTango
    - tango
  commands:                 # [unix]
    # Skip test_subscribe_data_ready_event on aarch64 for now
    # (fails most of the time)
    - pytest -v --forked                                           # [unix and not aarch64]
    - pytest -v --forked -k "not test_subscribe_data_ready_event"  # [aarch64]

about:
  home: http://pytango.rtfd.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - LICENSE.txt
  summary: Python binding for the TANGO control system
  doc_url: http://pytango.rtfd.io
  dev_url: https://gitlab.com/tango-controls/pytango

extra:
  recipe-maintainers:
    - beenje
    - ajoubertza
    - yamedvedya
