schema_version: 1

context:
  name: pytango
  version: 10.0.3rc1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 6cfa0adb57d3060dfa0a9e83a4a6bfc65a7140fc4c9c52c2eaa71b2e33a28606

build:
  number: 0
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - make
        - pkg-config
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=10.0.2,<10.1.0a0
    - libboost-python-devel
    - numpy
    - omniorb-libs
    - scikit-build-core
    - pybind11-stubgen
    - if: match(python, "<3.13")
      then: typing_extensions >=4.5.0
  run:
    - python
    - packaging
    - psutil >=5.3.0
    - if: match(python, "<3.13")
      then: typing_extensions >=4.5.0
    - if: unix
      then:
        - opentelemetry-api
        - opentelemetry-sdk
        - opentelemetry-exporter-otlp-proto-grpc
        - opentelemetry-exporter-otlp-proto-http

tests:
  - python:
      imports:
        - PyTango
        - tango
  - script:
      # Skip some flaky tests
      - if: unix and not aarch64
        then: pytest -k "not test_attribute_poll" || pytest --lf
      - if: aarch64
        then: pytest -k "not test_subscribe_data_ready_event and not test_attribute_poll and not test_databaseds.py" || pytest --lf
      # Only basic tests on windows
      - if: win
        then:
          - pytest -c pytest_win_config.toml tests/test_device_proxy.py::test_ping
          - pytest -c pytest_win_config.toml "tests/test_attribute_proxy.py::test_state_status[scalar_int]"
    files:
      source:
        - tests/
        - pyproject.toml
        - if: win
          then: pytest_win_config.toml
    requirements:
      run:
        - pytest
        - pytest-asyncio
        - pytest-forked
        - pytest-timeout
        - gevent
        - tango-test =3.11

about:
  summary: Python binding for the TANGO control system
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE.txt
  homepage: http://pytango.rtfd.io
  repository: https://gitlab.com/tango-controls/pytango
  documentation: http://pytango.rtfd.io

extra:
  recipe-maintainers:
    - yamedvedya
    - beenje
    - ajoubertza
