schema_version: 1

context:
  name: pytango
  version: 10.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 8f0b8905e40b990f8f2ce48bf47b072bfd7cb4578f144d158baddd001f98521d

build:
  number: 2
  skip: match(python, "<3.9")
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - if: build_platform != target_platform
      then: numpy
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - if: unix
      then: pkg-config
    - cmake
    - if: unix
      then: make
  host:
    - python
    - pip
    - cppzmq
    - cpptango >=10.0.2,<10.1.0a0
    - libboost-python-devel
    - numpy
    - omniorb-libs
    - scikit-build-core
    - pybind11-stubgen
    - if: match(python, "<3.13")
      then: typing_extensions >=4.5.0
  run:
    - python
    - packaging
    - psutil >=5.3.0
    - if: match(python, "<3.13")
      then: typing_extensions >=4.5.0
    - if: unix
      then: opentelemetry-api
    - if: unix
      then: opentelemetry-sdk
    - if: unix
      then: opentelemetry-exporter-otlp-proto-grpc
    - if: unix
      then: opentelemetry-exporter-otlp-proto-http

tests:
  - python:
      imports:
        - PyTango
        - tango
  - files:
      source:
        - if: unix
          then: tests/
        - if: unix
          then: pyproject.toml
    requirements:
      run:
        - if: unix
          then: pytest
        - if: unix
          then: pytest-asyncio
        - if: unix
          then: pytest-forked
        - if: unix
          then: gevent
        - if: unix
          then: tango-test =3.11
    script:
      - if: unix and not aarch64
        then: pytest -k "not test_attribute_poll" || pytest --lf
      - if: aarch64
        then: pytest -k "not test_subscribe_data_ready_event and not test_attribute_poll and not test_databaseds.py" || pytest --lf

about:
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE.txt
  summary: Python binding for the TANGO control system
  homepage: http://pytango.rtfd.io
  repository: https://gitlab.com/tango-controls/pytango
  documentation: http://pytango.rtfd.io

extra:
  recipe-maintainers:
    - yamedvedya
    - beenje
    - ajoubertza
